# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Promogroup
tagline: ''
description: ''
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/logo.png

facebook:
  username: oohweb

twitter:
  username:

linkedin:
  username:

youtube:
  username: creativapublicidad6131

google_business:
  username: Cfr23JqSYjRaEAI

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-google-tag-manager

languages: ['es', 'de', 'en', 'hu', 'sk']
language_default: 'es'
languageNames:
  es: Spanish
  de: Deutsch
  en: English
  hu: Magyar
  sk: Slovensk√°

sass:
  style: compressed

google:
  tag_manager:
    container_id: GTM-TCB89WNR

formspark_contact_form_action_url: https://submit-form.com/XO_0bqgeKLGtoPhyfu3tw

compress_html:
  clippings: all
  comments: ['<!-- ', ' -->']
  endings: all
  blanklines: false
  startings: [html, head, body]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package*.json
  - assets/js/partials/
  - README.md
